name: DEPENDABOT JIRA

on:
  pull_request:
    types:
      - opened
    branches:
      - master
jobs:
  build:
    name: Dependabot Jira
    runs-on: ubuntu-latest
    if: contains( github.event.pull_request.labels.*.name, 'dependencies')
    steps:
    - name: Login to Jira
      uses: atlassian/gajira-login@v2.0.0
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Create Jira Issue
      id: create
      uses: atlassian/gajira-create@v2.0.0
      with:
        project: ${{ secrets.JIRA_PROJECT_KEY }}
        issuetype: ${{ secrets.JIRA_ISSUE_TYPE }}
        summary: |
          ${{github.event.pull_request.title }}
        description: |
          ${{github.event.pull_request.body }}
